esphome:
  name: ${device_name}
  comment: ${friendly_name}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 1h
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    # ssid: "ESPHOME"
    ssid: ${device_name}
    password: !secret fallback_hotspot_password

captive_portal:

ota:
  password: !secret ota_password

logger:
  level: INFO

web_server:
  port: 80
  auth:
    username: !secret web_login
    password: !secret web_password

switch:
  - platform: restart
    name: reboot
    retain: false

sensor:
  - platform: wifi_signal
    id: wifi_signal_db
    name: rssi
    update_interval: 300s
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: signal
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
  - platform: uptime
    name: uptime

text_sensor:
  - platform: version
    name: esphome_version
  - platform: wifi_info
    ip_address:
      name: ip-address

mqtt:
  broker: !secret mqtt_broker
  discovery: false
  reboot_timeout: 1h
  id: mqtt_id
